#!/bin/sh

extensions=(
    aaron-bond.better-comments
    ahmadawais.shades-of-purple
    artlaman.chalice-icon-theme
    astro-build.astro-vscode
    batisteo.vscode-django
    be5invis.vscode-icontheme-nomo-dark
    bmalehorn.vscode-fish
    bradlc.vscode-tailwindcss
    castwide.solargraph
    catppuccin.catppuccin-vsc
    chadalen.vscode-jetbrains-icon-theme
    charliermarsh.ruff
    christian-kohler.npm-intellisense
    christian-kohler.path-intellisense
    codezombiech.gitignore
    damirka.move-syntax
    dart-code.dart-code
    dart-code.flutter
    davidanson.vscode-markdownlint
    dbaeumer.vscode-eslint
    denoland.vscode-deno
    donjayamanne.python-environment-manager
    donjayamanne.python-extension-pack
    drcika.apc-extension
    eamodio.gitlens
    ecmel.vscode-html-css
    editorconfig.editorconfig
    eliverlara.andromeda
    emmanuelbeziat.vscode-great-icons
    equinusocio.moxer-icons
    equinusocio.vsc-material-theme-icons
    esbenp.prettier-vscode
    fwcd.kotlin
    github.copilot
    github.copilot-chat
    github.vscode-github-actions
    github.vscode-pull-request-github
    gleam.gleam
    golang.go
    gruntfuggly.todo-tree
    helgardrichard.helium-icon-theme
    jakebecker.elixir-ls
    james-yu.latex-workshop
    jamesmaj.easy-icons
    jdinhlife.gruvbox
    kevinrose.vsc-python-indent
    mechatroner.rainbow-csv
    mikestead.dotenv
    move.move-analyzer
    ms-azuretools.vscode-docker
    ms-python.black-formatter
    ms-python.debugpy
    ms-python.flake8
    ms-python.isort
    ms-python.python
    ms-python.vscode-pylance
    ms-toolsai.jupyter
    ms-toolsai.jupyter-keymap
    ms-toolsai.jupyter-renderers
    ms-toolsai.vscode-jupyter-cell-tags
    ms-toolsai.vscode-jupyter-slideshow
    ms-vscode-remote.remote-containers
    ms-vscode.powershell
    ms-vsliveshare.vsliveshare
    msjsdiag.vscode-react-native
    njpwerner.autodocstring
    nomicfoundation.hardhat-solidity
    oven.bun-vscode
    patbenatar.advanced-new-file
    pkief.material-icon-theme
    pmndrs.pmndrs
    prisma.prisma
    puorc.awesome-vhdl
    qwtel.sqlite-viewer
    raunofreiberg.vesper
    redhat.vscode-yaml
    ritwickdey.liveserver
    robbowen.synthwave-vscode
    rust-lang.rust-analyzer
    sakai.sakai-icons
    sumneko.lua
    tailscale.vscode-tailscale
    tamasfe.even-better-toml
    tintinweb.vscode-vyper
    usernamehw.errorlens
    visualstudioexptteam.intellicode-api-usage-examples
    visualstudioexptteam.vscodeintellicode
    vscode-icons-team.vscode-icons
    vue.volar
    wakatime.vscode-wakatime
    wesbos.theme-cobalt2
    whizkydee.material-palenight-theme
    wholroyd.jinja
    yoavbls.pretty-ts-errors
    zhuangtongfa.material-theme
    ziglang.vscode-zig
    ziyasal.vscode-open-in-github
)

for extension in "${extensions[@]}"; do
    code --install-extension "$extension"
done

echo "VSCode extensions installed successfully!"
